[build-system]
build-backend = "mesonpy"
requires = ["meson-python", "cython"]

[project]
name = "subset"
version = "0.0.1"
requires-python = ">=3.11"
authors = [{ name = "Christer Sandberg", email = "chrsan@gmail.com" }]
license = { file = "../../LICENSE" }

[tool.meson-python.args]
install = ["--skip-subprojects"]
